server:
     port: 9000

connection:
    username: admin
    remoteAddress: 192.168.1.1
    server :
          dev : dev-server
          production : prod-server

spring:
    application:
        name: ZengCode
    freemarker:
        cache: false # This should be set to true in production.
